quarkus:
  log:
    console:
      format: "%d{HH:mm:ss,SSS} %-5p [%c{2.}] [%l] (%t) (%X) %s%e%n"
  vertx:
    prefer-native-transport: true
  hibernate-orm:
    enabled: false
  scheduler:
    enabled: false

ccs:
  server:
    computeSha256: true
  driverMaxChunkSize: 134217728
  driver:
    s3:
      maxPartSizeForUnknownLength: 10000000
