quarkus:
  log:
    console:
      format: "%d{HH:mm:ss,SSS} %-5p [%c{2.}] [%l] (%t) (%X) %s%e%n"

mp:
  messaging:
    incoming:
      replicator-request-in:
        connector: smallrye-kafka
        topic: ${CCS_REQUEST_REPLICATION:request-replication}
        retry-attempts: 10
        auto:
          offset:
            reset: earliest
        #broadcast: true
    outgoing:
      replicator-action-out:
        connector: smallrye-kafka
        topic: ${CCS_REQUEST_ACTION:request-action}
        retries: 10
        merge: true
